// Dummy product data
export const products = [
  {
    id: "1",
    name: "Classic White T-Shirt",
    description:
      "A timeless white t-shirt made from premium cotton for everyday comfort and style.",
    price: 29.99,
    category: "Men",
    subcategory: "T-Shirts",
    images: [
      "/placeholder.svg?height=400&width=400&text=White+T-Shirt",
      "/placeholder.svg?height=400&width=400&text=White+T-Shirt+2",
      "/placeholder.svg?height=400&width=400&text=White+T-Shirt+3",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Black", "Gray"],
    rating: 4.8,
    reviews: 124,
    inStock: true,
    tags: ["casual", "basics", "cotton"],
    featured: true,
    newArrival: false,
    discount: null,
    specifications: [
      { name: "Material", value: "100% Cotton" },
      { name: "Fit", value: "Regular" },
      { name: "Care", value: "Machine wash cold" },
    ],
  },
  {
    id: "2",
    name: "Slim Fit Jeans",
    description:
      "Modern slim fit jeans with a comfortable stretch for the perfect fit.",
    price: 59.99,
    category: "Men",
    subcategory: "Jeans",
    images: [
      "/placeholder.svg?height=400&width=400&text=Slim+Jeans",
      "/placeholder.svg?height=400&width=400&text=Slim+Jeans+2",
      "/placeholder.svg?height=400&width=400&text=Slim+Jeans+3",
    ],
    sizes: ["30", "32", "34", "36"],
    colors: ["Blue", "Black", "Gray"],
    rating: 4.5,
    reviews: 89,
    inStock: true,
    tags: ["casual", "denim", "stretch"],
    featured: true,
    newArrival: false,
    discount: null,
    specifications: [
      { name: "Material", value: "98% Cotton, 2% Elastane" },
      { name: "Fit", value: "Slim" },
      { name: "Rise", value: "Mid-rise" },
      { name: "Care", value: "Machine wash cold" },
    ],
  },
  {
    id: "3",
    name: "Floral Summer Dress",
    description:
      "A beautiful floral dress perfect for summer days and special occasions.",
    price: 49.99,
    category: "Women",
    subcategory: "Dresses",
    images: [
      "/placeholder.svg?height=400&width=400&text=Floral+Dress",
      "/placeholder.svg?height=400&width=400&text=Floral+Dress+2",
      "/placeholder.svg?height=400&width=400&text=Floral+Dress+3",
    ],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Blue", "Pink", "Yellow"],
    rating: 4.9,
    reviews: 156,
    inStock: true,
    tags: ["summer", "floral", "dress", "casual"],
    featured: true,
    newArrival: false,
    discount: 10,
    specifications: [
      { name: "Material", value: "100% Viscose" },
      { name: "Length", value: "Midi" },
      { name: "Fit", value: "Regular" },
      { name: "Care", value: "Hand wash cold" },
    ],
  },
  {
    id: "4",
    name: "Leather Crossbody Bag",
    description:
      "A stylish leather crossbody bag with multiple compartments for everyday use.",
    price: 79.99,
    category: "Accessories",
    subcategory: "Bags",
    images: [
      "/placeholder.svg?height=400&width=400&text=Leather+Bag",
      "/placeholder.svg?height=400&width=400&text=Leather+Bag+2",
      "/placeholder.svg?height=400&width=400&text=Leather+Bag+3",
    ],
    sizes: ["One Size"],
    colors: ["Brown", "Black", "Tan"],
    rating: 4.7,
    reviews: 68,
    inStock: true,
    tags: ["accessories", "leather", "bag"],
    featured: true,
    newArrival: false,
    discount: null,
    specifications: [
      { name: "Material", value: "Genuine Leather" },
      { name: "Dimensions", value: '9" x 6" x 2"' },
      { name: "Strap", value: "Adjustable" },
      { name: "Closure", value: "Zipper" },
    ],
  },
  {
    id: "5",
    name: "Oversized Knit Sweater",
    description:
      "A cozy oversized knit sweater perfect for layering in colder weather.",
    price: 69.99,
    category: "Women",
    subcategory: "Sweaters",
    images: [
      "/placeholder.svg?height=400&width=400&text=Knit+Sweater",
      "/placeholder.svg?height=400&width=400&text=Knit+Sweater+2",
      "/placeholder.svg?height=400&width=400&text=Knit+Sweater+3",
    ],
    sizes: ["S", "M", "L"],
    colors: ["Cream", "Gray", "Burgundy"],
    rating: 4.6,
    reviews: 92,
    inStock: true,
    tags: ["winter", "knitwear", "cozy"],
    featured: false,
    newArrival: true,
    discount: null,
    specifications: [
      { name: "Material", value: "70% Acrylic, 30% Wool" },
      { name: "Fit", value: "Oversized" },
      { name: "Neckline", value: "Crew neck" },
      { name: "Care", value: "Hand wash cold, lay flat to dry" },
    ],
  },
  {
    id: "6",
    name: "Athletic Running Shoes",
    description:
      "Lightweight running shoes with responsive cushioning for maximum comfort.",
    price: 89.99,
    category: "Men",
    subcategory: "Shoes",
    images: [
      "/placeholder.svg?height=400&width=400&text=Running+Shoes",
      "/placeholder.svg?height=400&width=400&text=Running+Shoes+2",
      "/placeholder.svg?height=400&width=400&text=Running+Shoes+3",
    ],
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: ["Black/White", "Blue/Gray", "Red/Black"],
    rating: 4.8,
    reviews: 215,
    inStock: true,
    tags: ["athletic", "running", "sports"],
    featured: false,
    newArrival: true,
    discount: null,
    specifications: [
      { name: "Material", value: "Synthetic mesh upper, rubber sole" },
      { name: "Cushioning", value: "Responsive foam" },
      { name: "Weight", value: "8.5 oz" },
      { name: "Drop", value: "8mm" },
    ],
  },
  {
    id: "7",
    name: "Structured Blazer",
    description:
      "A tailored blazer that transitions seamlessly from office to evening.",
    price: 129.99,
    category: "Women",
    subcategory: "Jackets",
    images: [
      "/placeholder.svg?height=400&width=400&text=Blazer",
      "/placeholder.svg?height=400&width=400&text=Blazer+2",
      "/placeholder.svg?height=400&width=400&text=Blazer+3",
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Beige"],
    rating: 4.7,
    reviews: 78,
    inStock: true,
    tags: ["formal", "office", "blazer"],
    featured: false,
    newArrival: true,
    discount: null,
    specifications: [
      { name: "Material", value: "97% Cotton, 3% Elastane" },
      { name: "Fit", value: "Slim fit" },
      { name: "Closure", value: "Button" },
      { name: "Care", value: "Dry clean only" },
    ],
  },
  {
    id: "8",
    name: "Polarized Sunglasses",
    description:
      "Stylish polarized sunglasses that provide 100% UV protection.",
    price: 119.99,
    category: "Accessories",
    subcategory: "Sunglasses",
    images: [
      "/placeholder.svg?height=400&width=400&text=Sunglasses",
      "/placeholder.svg?height=400&width=400&text=Sunglasses+2",
      "/placeholder.svg?height=400&width=400&text=Sunglasses+3",
    ],
    sizes: ["One Size"],
    colors: ["Black", "Tortoise", "Gold"],
    rating: 4.9,
    reviews: 45,
    inStock: true,
    tags: ["accessories", "sunglasses", "summer"],
    featured: false,
    newArrival: true,
    discount: null,
    specifications: [
      { name: "Frame", value: "Acetate" },
      { name: "Lens", value: "Polarized" },
      { name: "Protection", value: "100% UV" },
      { name: "Dimensions", value: "52-20-145mm" },
    ],
  },
  {
    id: "9",
    name: "Hooded Parka Jacket",
    description:
      "A warm and waterproof parka jacket with hood for cold weather protection.",
    price: 149.99,
    category: "Men",
    subcategory: "Jackets",
    images: [
      "/placeholder.svg?height=400&width=400&text=Parka+Jacket",
      "/placeholder.svg?height=400&width=400&text=Parka+Jacket+2",
      "/placeholder.svg?height=400&width=400&text=Parka+Jacket+3",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Olive", "Black", "Navy"],
    rating: 4.8,
    reviews: 112,
    inStock: true,
    tags: ["winter", "outerwear", "waterproof"],
    featured: false,
    newArrival: false,
    discount: 15,
    specifications: [
      {
        name: "Material",
        value:
          "Shell: 100% Polyester, Lining: 100% Polyester, Fill: 80% Down, 20% Feather",
      },
      { name: "Waterproof", value: "Yes" },
      { name: "Closure", value: "Zipper and snap buttons" },
      { name: "Care", value: "Machine wash cold" },
    ],
  },
  {
    id: "10",
    name: "High-Waisted Yoga Leggings",
    description:
      "Comfortable high-waisted yoga leggings with four-way stretch and moisture-wicking fabric.",
    price: 49.99,
    category: "Women",
    subcategory: "Activewear",
    images: [
      "/placeholder.svg?height=400&width=400&text=Yoga+Leggings",
      "/placeholder.svg?height=400&width=400&text=Yoga+Leggings+2",
      "/placeholder.svg?height=400&width=400&text=Yoga+Leggings+3",
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Burgundy", "Gray"],
    rating: 4.9,
    reviews: 230,
    inStock: true,
    tags: ["activewear", "yoga", "workout"],
    featured: false,
    newArrival: false,
    discount: null,
    specifications: [
      { name: "Material", value: "76% Polyester, 24% Spandex" },
      { name: "Rise", value: "High-waisted" },
      { name: "Length", value: "Full length" },
      {
        name: "Features",
        value: "Four-way stretch, moisture-wicking, hidden pocket",
      },
    ],
  },
  {
    id: "11",
    name: "Leather Watch",
    description:
      "A classic leather watch with a minimalist design suitable for any occasion.",
    price: 129.99,
    category: "Accessories",
    subcategory: "Watches",
    images: [
      "/placeholder.svg?height=400&width=400&text=Leather+Watch",
      "/placeholder.svg?height=400&width=400&text=Leather+Watch+2",
      "/placeholder.svg?height=400&width=400&text=Leather+Watch+3",
    ],
    sizes: ["One Size"],
    colors: ["Brown/Gold", "Black/Silver"],
    rating: 4.7,
    reviews: 86,
    inStock: true,
    tags: ["accessories", "watch", "leather"],
    featured: false,
    newArrival: false,
    discount: null,
    specifications: [
      { name: "Case Material", value: "Stainless Steel" },
      { name: "Band Material", value: "Genuine Leather" },
      { name: "Movement", value: "Quartz" },
      { name: "Water Resistance", value: "3 ATM" },
    ],
  },
  {
    id: "12",
    name: "Button-Down Oxford Shirt",
    description:
      "A classic button-down oxford shirt perfect for both casual and formal occasions.",
    price: 59.99,
    category: "Men",
    subcategory: "Shirts",
    images: [
      "/placeholder.svg?height=400&width=400&text=Oxford+Shirt",
      "/placeholder.svg?height=400&width=400&text=Oxford+Shirt+2",
      "/placeholder.svg?height=400&width=400&text=Oxford+Shirt+3",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White", "Blue", "Pink"],
    rating: 4.6,
    reviews: 104,
    inStock: true,
    tags: ["formal", "casual", "button-down"],
    featured: false,
    newArrival: false,
    discount: null,
    specifications: [
      { name: "Material", value: "100% Cotton" },
      { name: "Fit", value: "Regular fit" },
      { name: "Collar", value: "Button-down" },
      { name: "Care", value: "Machine wash cold" },
    ],
  },
];

// Dummy categories data
export const categories = [
  {
    id: "men",
    name: "Men",
    description: "Clothing and accessories for men",
    image: "/placeholder.svg?height=400&width=400&text=Men",
    subcategories: ["T-Shirts", "Shirts", "Jeans", "Pants", "Jackets", "Shoes"],
  },
  {
    id: "women",
    name: "Women",
    description: "Clothing and accessories for women",
    image: "/placeholder.svg?height=400&width=400&text=Women",
    subcategories: ["Dresses", "Tops", "Skirts", "Pants", "Jackets", "Shoes"],
  },
  {
    id: "accessories",
    name: "Accessories",
    description: "Fashion accessories for men and women",
    image: "/placeholder.svg?height=400&width=400&text=Accessories",
    subcategories: [
      "Bags",
      "Watches",
      "Sunglasses",
      "Jewelry",
      "Hats",
      "Belts",
    ],
  },
];

// Dummy orders data
export const orders = [
  {
    id: "ORD-1234",
    date: "2023-05-15T10:30:00Z",
    status: "Delivered",
    total: 159.97,
    items: [
      {
        id: "1",
        name: "Classic White T-Shirt",
        price: 29.99,
        quantity: 2,
        image: "/placeholder.svg?height=400&width=400&text=White+T-Shirt",
      },
      {
        id: "4",
        name: "Leather Crossbody Bag",
        price: 79.99,
        quantity: 1,
        image: "/placeholder.svg?height=400&width=400&text=Leather+Bag",
      },
    ],
    shippingAddress: {
      name: "John Doe",
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zipCode: "10001",
      country: "United States",
    },
    paymentMethod: "Credit Card",
  },
  {
    id: "ORD-5678",
    date: "2023-06-20T14:45:00Z",
    status: "Processing",
    total: 219.97,
    items: [
      {
        id: "7",
        name: "Structured Blazer",
        price: 129.99,
        quantity: 1,
        image: "/placeholder.svg?height=400&width=400&text=Blazer",
      },
      {
        id: "10",
        name: "High-Waisted Yoga Leggings",
        price: 49.99,
        quantity: 1,
        image: "/placeholder.svg?height=400&width=400&text=Yoga+Leggings",
      },
      {
        id: "3",
        name: "Floral Summer Dress",
        price: 49.99,
        quantity: 1,
        image: "/placeholder.svg?height=400&width=400&text=Floral+Dress",
      },
    ],
    shippingAddress: {
      name: "John Doe",
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zipCode: "10001",
      country: "United States",
    },
    paymentMethod: "PayPal",
  },
  {
    id: "ORD-9012",
    date: "2023-07-05T09:15:00Z",
    status: "Shipped",
    total: 89.99,
    items: [
      {
        id: "6",
        name: "Athletic Running Shoes",
        price: 89.99,
        quantity: 1,
        image: "/placeholder.svg?height=400&width=400&text=Running+Shoes",
      },
    ],
    shippingAddress: {
      name: "John Doe",
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zipCode: "10001",
      country: "United States",
    },
    paymentMethod: "Credit Card",
  },
];

// Dummy reviews data
export const reviews = [
  {
    id: "1",
    productId: "1",
    user: "Sarah J.",
    rating: 5,
    title: "Perfect fit and great quality",
    comment:
      "This t-shirt is exactly what I was looking for. The material is soft and comfortable, and the fit is perfect. Highly recommend!",
    date: "2023-04-10T08:30:00Z",
    helpful: 12,
  },
  {
    id: "2",
    productId: "1",
    user: "Michael T.",
    rating: 4,
    title: "Good quality but runs small",
    comment:
      "The quality of the t-shirt is great, but it runs a bit small. I would recommend sizing up if you're between sizes.",
    date: "2023-03-25T14:15:00Z",
    helpful: 8,
  },
  {
    id: "3",
    productId: "2",
    user: "David L.",
    rating: 5,
    title: "Best jeans I've ever owned",
    comment:
      "These jeans are amazing! The stretch makes them super comfortable, and they look great. Will definitely buy more colors.",
    date: "2023-05-02T11:45:00Z",
    helpful: 15,
  },
  {
    id: "4",
    productId: "3",
    user: "Emily R.",
    rating: 5,
    title: "Beautiful summer dress",
    comment:
      "This dress is perfect for summer! The floral pattern is beautiful, and the material is light and breathable. I've received many compliments.",
    date: "2023-06-15T09:20:00Z",
    helpful: 20,
  },
  {
    id: "5",
    productId: "4",
    user: "Jessica M.",
    rating: 4,
    title: "Stylish and functional",
    comment:
      "This bag is both stylish and functional. The leather is high quality, and there are plenty of compartments. The only reason for 4 stars is that the strap could be a bit longer.",
    date: "2023-05-20T16:30:00Z",
    helpful: 7,
  },
];

// Dummy user addresses
export const addresses = [
  {
    id: "1",
    name: "John Doe",
    street: "123 Main St",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    country: "United States",
    isDefault: true,
    type: "Home",
  },
  {
    id: "2",
    name: "John Doe",
    street: "456 Market St",
    city: "San Francisco",
    state: "CA",
    zipCode: "94103",
    country: "United States",
    isDefault: false,
    type: "Work",
  },
];
